# Generated by Django 6.0.5 on 2026-05-29 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('icon', models.CharField(help_text="lucide-react icon name in PascalCase (e.g. 'Wrench').", max_length=40)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('accent', models.CharField(default='#eab308', help_text='Hex accent color.', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('headline', models.CharField(max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField()),
                ('cover_url', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('jobs_done', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('city', models.CharField(max_length=80)),
                ('neighborhood', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
                ('top_rated', models.BooleanField(default=False)),
                ('response_time', models.CharField(default='em 1 hora', max_length=40)),
                ('availability', models.CharField(default='Disponível esta semana', max_length=60)),
                ('skills', models.JSONField(default=list)),
                ('member_since', models.PositiveIntegerField(default=2022)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'ordering': ['-top_rated', '-rating', '-reviews_count'],
            },
        ),
    ]
