# Generated by Django 6.0.5 on 2026-06-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_provider_avatar_provider_status_availabilityslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpf_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cpf_status',
            field=models.CharField(choices=[('verified', 'Verificado'), ('pending_verification', 'Pendente de verificação'), ('mismatch', 'Nome não confere com o CPF')], default='pending_verification', max_length=30),
        ),
    ]
