# Generated by Django 6.0.5 on 2026-06-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_userprofile_cpf_name_userprofile_cpf_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='provider_status',
            field=models.CharField(blank=True, choices=[('', 'Não é prestador'), ('pending', 'Pendente de aprovação'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='', max_length=20),
        ),
    ]
