# Generated by Django 6.0.5 on 2026-06-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_userprofile_provider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
