# Generated by Django 6.0.5 on 2026-06-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_provider_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='member_since',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
