# Generated by Django 6.0.5 on 2026-06-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_providerswipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerswipe',
            name='source',
            field=models.CharField(choices=[('deck', 'Deck de recomendações'), ('profile', 'Perfil do prestador')], default='deck', max_length=10),
        ),
    ]
