# Generated by Django 6.0.5 on 2026-06-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_providerswipe_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag de serviço',
                'verbose_name_plural': 'Tags de serviço',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='providers', to='catalog.tag'),
        ),
    ]
