# Generated by Django 6.0.5 on 2026-06-15 04:27

from django.db import migrations
from django.utils.text import slugify


def seed_tags(apps, schema_editor):
    """Cria tags a partir das skills (texto livre) já existentes nos prestadores e
    associa cada prestador às suas tags. Assim o vocabulário de tags nasce povoado
    e o autocomplete já tem sugestões reais."""
    Provider = apps.get_model("catalog", "Provider")
    Tag = apps.get_model("catalog", "Tag")

    for provider in Provider.objects.all():
        tag_ids = []
        for raw in provider.skills or []:
            name = (raw or "").strip()
            if not name:
                continue
            slug = slugify(name)[:60]
            if not slug:
                continue
            tag, _ = Tag.objects.get_or_create(slug=slug, defaults={"name": name[:50]})
            tag_ids.append(tag.id)
        if tag_ids:
            provider.tags.add(*tag_ids)


def unseed_tags(apps, schema_editor):
    Tag = apps.get_model("catalog", "Tag")
    Tag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_tag_provider_tags"),
    ]

    operations = [
        migrations.RunPython(seed_tags, unseed_tags),
    ]
