# Generated by Django 6.0.5 on 2026-06-15 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_seed_tags_from_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('provider_approved', 'Perfil aprovado'), ('provider_rejected', 'Perfil rejeitado'), ('cpf_verified', 'CPF verificado'), ('cpf_mismatch', 'CPF não confere'), ('order_requested', 'Nova solicitação de serviço'), ('order_confirmed', 'Serviço confirmado'), ('order_in_progress', 'Serviço em andamento'), ('order_completed', 'Serviço concluído'), ('order_cancelled', 'Serviço cancelado'), ('order_disputed', 'Disputa aberta'), ('order_reviewed', 'Serviço avaliado'), ('new_message', 'Nova mensagem'), ('new_provider_in_area', 'Novo profissional na sua área'), ('recommendation', 'Recomendação para você')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='catalog_not_recipie_507b8b_idx'), models.Index(fields=['recipient', '-created_at'], name='catalog_not_recipie_b761d9_idx')],
            },
        ),
    ]
