# Generated by Django 6.0.5 on 2026-06-15 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_supportcategory_faqarticle_supportticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('neighborhood', models.CharField(blank=True, default='', max_length=80)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('preferred_schedule', models.CharField(blank=True, default='', help_text="Ex.: 'Segunda-feira de manhã' ou 'Até 15 de julho'", max_length=160)),
                ('budget_hint', models.CharField(blank=True, default='', help_text="Ex.: 'Até R$ 500' ou 'A combinar'", max_length=80)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em andamento'), ('closed', 'Encerrada'), ('cancelled', 'Cancelada')], default='open', max_length=20)),
                ('offer_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='catalog.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='demands', to='catalog.tag')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=200)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('cliente_telefone', models.CharField(blank=True, max_length=15)),
                ('descricao', models.TextField()),
                ('endereco', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_solicitada', models.DateTimeField()),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('valor_combinado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissao_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('solicitado', 'Pendente de aprovação'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('em_andamento', 'Em andamento'), ('concluido', 'Aguardando confirmação'), ('aguardando_pagamento', 'Aguardando pagamento'), ('finalizado', 'Finalizado'), ('disputa', 'Em disputa')], db_index=True, default='solicitado', max_length=24)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('sugestao_horario', models.DateTimeField(blank=True, null=True)),
                ('pix_copia_cola', models.TextField(blank=True)),
                ('pago', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_contratados', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='catalog.provider')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.provider')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_feitas', to=settings.AUTH_USER_MODEL)),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='catalog.servico')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', help_text='Mensagem do prestador para o cliente')),
                ('suggested_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Recusado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.demand')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_offers', to='catalog.provider')),
            ],
            options={
                'verbose_name': 'Oferta de demanda',
                'verbose_name_plural': 'Ofertas de demandas',
                'ordering': ['-created_at'],
                'unique_together': {('demand', 'provider')},
            },
        ),
    ]
