import { chromium } from "playwright-core";
const OUT = "c:/Users/guipa/Documents/HIVEE SITE/frontend/_shots";
const BASE = "http://127.0.0.1:5201";
const browser = await chromium.launch({ channel: "msedge", headless: true });
const page = await browser.newContext({ viewport: { width: 1366, height: 860 } }).then((c) => c.newPage());
await page.goto(BASE + "/", { waitUntil: "networkidle" });
await page.waitForTimeout(2800);
await page.screenshot({ path: `${OUT}/cine-0.png` });
await page.evaluate(() => window.scrollTo(0, 260));
await page.waitForTimeout(900);
await page.screenshot({ path: `${OUT}/cine-mid.png` });
console.log("done");
await browser.close();
