# Generated by Django 6.0.5 on 2026-06-15 01:39

import logging
import django.db.models.deletion
from django.db import migrations, models

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0009_alter_provider_member_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, unique=True, verbose_name='Telefone/ID')),
                ('nome_wpp', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome WhatsApp')),
                ('nome_site', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome no Site')),
                ('canal_origem', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('site', 'Site')], default='whatsapp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead do Chat',
                'verbose_name_plural': 'Leads do Chat',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('site', 'Site')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('closed', 'Encerrado')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_recomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.provider', verbose_name='Prestador recomendado')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='agent.chatlead')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('bot', 'Bot'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('msg_type', models.CharField(choices=[('text', 'Texto'), ('audio', 'Audio'), ('image', 'Imagem')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='agent.chat')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
    ]
