# Generated by Django 6.0.3 on 2026-04-28 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(choices=[('⚡', 'Elétrica'), ('🔧', 'Hidráulica'), ('🧹', 'Limpeza'), ('🎨', 'Pintura'), ('🪚', 'Marcenaria'), ('❄️', 'Ar-Condicionado'), ('🏠', 'Reforma Geral'), ('📦', 'Mudança'), ('🌿', 'Jardinagem'), ('🔒', 'Segurança'), ('💻', 'Tecnologia'), ('🔨', 'Outros')], default='🔨', max_length=5)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PrestadorPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Apresentação curta (máx. 500 caracteres)', max_length=500)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='prestadores/fotos/%Y/%m/')),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(default='', max_length=2)),
                ('anos_experiencia', models.PositiveIntegerField(default=0)),
                ('disponivel', models.BooleanField(default=True)),
                ('status_adesao', models.CharField(choices=[('PENDENTE', 'Pendente de Pagamento'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso')], default='PENDENTE', max_length=10)),
                ('data_adesao', models.DateField(blank=True, null=True)),
                ('total_servicos', models.PositiveIntegerField(default=0)),
                ('nota_media', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('especialidades', models.ManyToManyField(blank=True, related_name='prestadores', to='servicos.categoriaservico')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestador_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Prestador',
                'verbose_name_plural': 'Perfis de Prestadores',
                'ordering': ['-nota_media', '-total_servicos'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('endereco_servico', models.CharField(max_length=300)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_agendada', models.DateField(blank=True, null=True)),
                ('hora_agendada', models.TimeField(blank=True, null=True)),
                ('horas_estimadas', models.PositiveIntegerField(default=1)),
                ('valor_acordado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito pelo Prestador'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('DISPUTADO', 'Em Disputa')], default='PENDENTE', max_length=15)),
                ('data_aceite', models.DateTimeField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status_pagamento', models.CharField(choices=[('AGUARDANDO', 'Aguardando pagamento'), ('RETIDO', 'Retido (Escrow)'), ('LIBERADO', 'Liberado ao Prestador'), ('REEMBOLSADO', 'Reembolsado ao Cliente')], default='AGUARDANDO', max_length=15)),
                ('observacoes_prestador', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.categoriaservico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='servicos.prestadorperfil')),
            ],
            options={
                'verbose_name': 'Contrato de Serviço',
                'verbose_name_plural': 'Contratos de Serviços',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True, max_length=1000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='servicos.contrato')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='servicos.prestadorperfil')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PRESTADOR', 'Prestador de Serviço')], default='CLIENTE', max_length=10)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('plano', models.CharField(choices=[('BASICO', 'Basic — R$ 9,99/mês'), ('PREMIUM', 'Premium — R$ 100,00/mês'), ('NENHUM', 'Sem plano')], default='NENHUM', max_length=10)),
                ('servicos_usados_mes', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
