# Generated by Django 6.0.3 on 2026-05-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_categoriaproduto_produto_prestadorperfil_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadorperfil',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
